version: "3.7"

services:
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
    web:
#        build:
#            context: .
#            dockerfile: client/Dockerfile
        depends_on:
            -   back
        container_name: front
        image: burmatovdd/bonds-client:0.1.2_amd64
        ports:
            - 80:80
    back:
#        build:
#            context: .
#            dockerfile: Dockerfile
        depends_on:
            - redis
            - mongodb
        container_name: back
        image: burmatovdd/bonds-server:0.2.2_amd64
#        ports:
#            - 1234:8080
        environment:
            - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
            - REDIS_CONN=redis:6379
    mongodb:
        image: mongo:5.0
        ports:
            - 4321:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
            - MONGO_INITDB_ROOT_PASSWORD=hunter2
        volumes:
            - ./data:/data/db

    sendMail:
        depends_on:
            -  redis
        container_name: mail
        image: burmatovdd/sendmail:0.0.4_amd64
        environment:
            - REDIS_CONN=redis:6379


